title: Habibi Saifuddin # your name (or website title) here
logo: "/images/selfie.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Originally graduated as a Physics Engineer currently in learning phase about Data Science and in persue of a career as a Data Scientist.
  <br><br>
  Currently live in Bali, Indonesia.<br>
  In this portofolio are some of my projects in Data Science, so feel free to read and contact me for some feedbacks via contacts provided in latter section. 
  <br><br>
  <a href="https://www.linkedin.com/in/habibi-saifuddin-a90496121/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
